FROM ubuntu:22.04

RUN apt update
RUN apt install -y libstdc++6 build-essential git cmake g++

ARG BUILDDIR=/src/${PROJECT_BINARY_NAME}-build-docker-singlerun

RUN --mount=from=project,target=/src/${PROJECT_BINARY_NAME} \ 
 cd /src/${PROJECT_BINARY_NAME} && \
 mkdir -vp $BUILDDIR && \
 cmake -S . -B $BUILDDIR -DCMAKE_BUILD_TYPE=Release &&  \
 cmake --build $BUILDDIR -j$(nproc) --target ${PROJECT_BINARY_NAME} && \
 cmake --install $BUILDDIR --prefix /usr

CMD ["${PROJECT_BINARY_NAME}"]
