cmake_minimum_required(VERSION 3.13)

set(YOLO4_TRAINER_STARTER_SCRIPT ${CMAKE_CURRENT_SOURCE_DIR}/darknet-trainer.sh)
set(DARKNETXX_TRAINER_STARTER_SCRIPT ${CMAKE_CURRENT_SOURCE_DIR}/darknetxx-trainer.sh.cmake.in)
set(DARKNET_PREDICTOR_STARTER_SCRIPT ${CMAKE_CURRENT_SOURCE_DIR}/darknet-predictor.sh)
set(DARKNETXX_PREDICTOR_STARTER_SCRIPT ${CMAKE_CURRENT_SOURCE_DIR}/darknetxx-predictor.sh)

if(ENABLE_DOCKER_DARKNET)
  message(STATUS "YOLO4_TRAINER_STARTER_SCRIPT: ${YOLO4_TRAINER_STARTER_SCRIPT}")
  install(
    FILES ${YOLO4_TRAINER_STARTER_SCRIPT}
    DESTINATION bin
    PERMISSIONS OWNER_READ OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE
  )
endif()

if(ENABLE_DOCKER_DARKNET_PREDICTOR)
  message(STATUS "DARKNET_PREDICTOR_STARTER_SCRIPT: ${DARKNET_PREDICTOR_STARTER_SCRIPT}")
  install(
    FILES ${DARKNET_PREDICTOR_STARTER_SCRIPT}
    DESTINATION bin
    PERMISSIONS OWNER_READ OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE
  )
endif()

if (ENABLE_DOCKER_DARKNETXX_CPU_TRAIN)
  message(STATUS "DARKNETXX_TRAINER_STARTER_SCRIPT: ${DARKNETXX_TRAINER_STARTER_SCRIPT}")
  configure_file(${DARKNETXX_TRAINER_STARTER_SCRIPT} darknetxx-trainer.sh @ONLY)
  install(
    FILES ${CMAKE_CURRENT_BINARY_DIR}/darknetxx-trainer.sh
    DESTINATION bin
    PERMISSIONS OWNER_READ OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE
  )
endif()

if(ENABLE_DOCKER_DARKNETXX_PREDICTOR)
  message(STATUS "DARKNETXX_PREDICTOR_STARTER_SCRIPT: ${DARKNETXX_PREDICTOR_STARTER_SCRIPT}")
  install(
    FILES ${DARKNETXX_PREDICTOR_STARTER_SCRIPT}
    DESTINATION bin
    PERMISSIONS OWNER_READ OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE
  )
endif()

