cmake_minimum_required(VERSION 3.13)

option(
  ENABLE_FREEBSD_PKG
  "Set to ON to enable the FreeBSD pkg package creation from the project build artifacts"
  OFF
)

if(NOT ENABLE_FREEBSD_PKG)
    return()
endif()

include(InstallRequiredSystemLibraries)

set(
  TEMPLATE_PROJECT_FREEBSD_PKG_LICENSE
  "BSD2CLAUSE"
  CACHE STRING
  "FreeBSD pkg license tag (e.g. BSD2CLAUSE, BSD3CLAUSE, GPLv3, MIT)"
)

set(
  TEMPLATE_PROJECT_FREEBSD_PKG_ORIGIN
  "misc/${PROJECT_BINARY_NAME_lower}"
  CACHE STRING
  "FreeBSD pkg origin in <category>/<name> form"
)

set(
  TEMPLATE_PROJECT_FREEBSD_PKG_CATEGORIES
  "misc"
  CACHE STRING
  "Semicolon-separated list of FreeBSD pkg categories"
)

set(CPACK_GENERATOR "FREEBSD")
set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_CONTACT ${PROJECT_MAINTAINER_EMAIL})
set(CPACK_PACKAGE_VENDOR "${PROJECT_MAINTAINER}")
set(CPACK_PACKAGE_DESCRIPTION ${CMAKE_PROJECT_DESCRIPTION})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY ${CMAKE_PROJECT_DESCRIPTION})

set(CPACK_FREEBSD_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_FREEBSD_PACKAGE_COMMENT ${CMAKE_PROJECT_DESCRIPTION})
set(CPACK_FREEBSD_PACKAGE_DESCRIPTION ${CMAKE_PROJECT_DESCRIPTION})
set(CPACK_FREEBSD_PACKAGE_WWW ${CMAKE_PROJECT_HOMEPAGE_URL})
set(CPACK_FREEBSD_PACKAGE_LICENSE ${TEMPLATE_PROJECT_FREEBSD_PKG_LICENSE})
set(CPACK_FREEBSD_PACKAGE_MAINTAINER "${PROJECT_MAINTAINER_EMAIL}")
set(CPACK_FREEBSD_PACKAGE_ORIGIN ${TEMPLATE_PROJECT_FREEBSD_PKG_ORIGIN})
set(CPACK_FREEBSD_PACKAGE_CATEGORIES ${TEMPLATE_PROJECT_FREEBSD_PKG_CATEGORIES})
set(CPACK_FREEBSD_PACKAGE_DEPS "")

include(CPack)
