cmake_minimum_required(VERSION 3.13)

option(
  ENABLE_RPM
  "Set to ON to enable the RPM package creation from the project build artifacts"
  OFF
)

if(NOT ENABLE_RPM)
    return()
endif()

include(InstallRequiredSystemLibraries)

set(
  TEMPLATE_PROJECT_RPM_LICENSE
  "BSD-2-Clause"
  CACHE STRING
  "RPM package license tag (e.g. BSD-2-Clause, BSD-3-Clause, GPLv3, MIT, Apache-2.0)"
)

set(
  TEMPLATE_PROJECT_RPM_GROUP
  "Applications/System"
  CACHE STRING
  "RPM package group (e.g. Applications/System, Development/Libraries)"
)

set(
  TEMPLATE_PROJECT_RPM_RELEASE
  "1"
  CACHE STRING
  "RPM package release number (incremented across rebuilds of the same upstream version)"
)

set(
  TEMPLATE_PROJECT_RPM_PACKAGE_ARCHITECTURE
  "x86_64"
  CACHE STRING
  "RPM package architecture tag (e.g. x86_64, aarch64, noarch)"
)

set(CPACK_GENERATOR "RPM")
set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_CONTACT ${PROJECT_MAINTAINER_EMAIL})
set(CPACK_PACKAGE_VENDOR "${PROJECT_MAINTAINER}")
set(CPACK_PACKAGE_DESCRIPTION ${CMAKE_PROJECT_DESCRIPTION})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY ${CMAKE_PROJECT_DESCRIPTION})

set(CPACK_RPM_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_RPM_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_RPM_PACKAGE_LICENSE ${TEMPLATE_PROJECT_RPM_LICENSE})
set(CPACK_RPM_PACKAGE_GROUP ${TEMPLATE_PROJECT_RPM_GROUP})
set(CPACK_RPM_PACKAGE_RELEASE ${TEMPLATE_PROJECT_RPM_RELEASE})
set(CPACK_RPM_PACKAGE_URL ${CMAKE_PROJECT_HOMEPAGE_URL})
set(CPACK_RPM_PACKAGE_SUMMARY ${CMAKE_PROJECT_DESCRIPTION})
set(CPACK_RPM_PACKAGE_DESCRIPTION ${CMAKE_PROJECT_DESCRIPTION})
set(CPACK_RPM_PACKAGE_VENDOR "${PROJECT_MAINTAINER}")
set(CPACK_RPM_PACKAGE_ARCHITECTURE ${TEMPLATE_PROJECT_RPM_PACKAGE_ARCHITECTURE})
set(CPACK_RPM_PACKAGE_REQUIRES "")
set(CPACK_RPM_COMPONENT_INSTALL ON)

include(CPack)
