#!/usr/bin/env bash

export CUDA_VERSION="12.6"
export CUDNN_VERSION="9.0"

export CUDA_VERSION_DASHED="${CUDA_VERSION//./-}"
export CUDA_MAJOR_VERSION="${CUDA_VERSION%%.*}"
export CUDA_MINOR_VERSION="${CUDA_VERSION#*.}"
export CUDNN_VERSION_DASHED="${CUDNN_VERSION//./-}"
export CUDNN_MAJOR_VERSION="${CUDNN_VERSION%%.*}"
export CUDNN_MINOR_VERSION="${CUDNN_VERSION#*.}"
